create extension if not exists pgcrypto;
create table public.businesses(id uuid primary key default gen_random_uuid(),name text not null,country text not null default 'Nicaragua',base_currency text not null default 'NIO',initial_capital_usd numeric(14,2) not null default 4100,created_at timestamptz not null default now());
create table public.business_users(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,user_id uuid not null references auth.users on delete cascade,role text not null check(role in ('owner','admin','employee','accountant','viewer')),unique(business_id,user_id));
create table public.customers(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,name text not null,phone text,email text,created_at timestamptz default now());
create table public.products(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,sku text,name text not null,category text,stock numeric(14,3) not null default 0,min_stock numeric(14,3) not null default 0,cost numeric(14,2) not null default 0,price numeric(14,2) not null default 0,currency text not null default 'USD',created_at timestamptz default now());
create table public.financial_accounts(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,name text not null,type text not null check(type in ('bank','cash')),currency text not null check(currency in ('NIO','USD')),opening_balance numeric(14,2) not null default 0);
create table public.sales(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,customer_id uuid references public.customers,number text not null,currency text not null check(currency in ('NIO','USD')),exchange_rate numeric(14,6) not null,total numeric(14,2) not null default 0,paid numeric(14,2) not null default 0,status text not null default 'open',created_at timestamptz default now(),unique(business_id,number));
create table public.sale_items(id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.sales on delete cascade,product_id uuid references public.products,description text not null,quantity numeric(14,3) not null,unit_price numeric(14,2) not null,cost numeric(14,2) not null default 0);
create table public.expenses(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,account_id uuid references public.financial_accounts,category text not null,description text,amount numeric(14,2) not null,currency text not null,exchange_rate numeric(14,6) not null,expense_date date not null default current_date,created_at timestamptz default now());
create table public.inventory_movements(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,product_id uuid not null references public.products,type text not null,quantity numeric(14,3) not null,unit_cost numeric(14,2) not null default 0,reference text,created_at timestamptz default now());
create table public.chart_of_accounts(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,code text not null,name text not null,type text not null,unique(business_id,code));
create table public.journal_entries(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses on delete cascade,entry_date date not null default current_date,memo text,reference text,created_at timestamptz default now());
create table public.journal_lines(id uuid primary key default gen_random_uuid(),entry_id uuid not null references public.journal_entries on delete cascade,account_id uuid not null references public.chart_of_accounts,debit numeric(14,2) not null default 0,credit numeric(14,2) not null default 0,check(debit>=0 and credit>=0 and not(debit>0 and credit>0)));
create table public.audit_logs(id bigserial primary key,business_id uuid not null references public.businesses on delete cascade,user_id uuid references auth.users,action text not null,entity text,entity_id uuid,created_at timestamptz default now());

alter table public.businesses enable row level security; alter table public.business_users enable row level security; alter table public.customers enable row level security; alter table public.products enable row level security; alter table public.financial_accounts enable row level security; alter table public.sales enable row level security; alter table public.sale_items enable row level security; alter table public.expenses enable row level security; alter table public.inventory_movements enable row level security; alter table public.chart_of_accounts enable row level security; alter table public.journal_entries enable row level security; alter table public.journal_lines enable row level security; alter table public.audit_logs enable row level security;

grant select,insert,update,delete on public.businesses,public.business_users,public.customers,public.products,public.financial_accounts,public.sales,public.sale_items,public.expenses,public.inventory_movements,public.chart_of_accounts,public.journal_entries,public.journal_lines to authenticated;
grant select,insert on public.audit_logs to authenticated;

create policy business_member_select on public.businesses for select to authenticated using (exists(select 1 from public.business_users bu where bu.business_id=id and bu.user_id=(select auth.uid())));
create policy business_member_data on public.customers for all to authenticated using (exists(select 1 from public.business_users bu where bu.business_id=customers.business_id and bu.user_id=(select auth.uid()))) with check (exists(select 1 from public.business_users bu where bu.business_id=customers.business_id and bu.user_id=(select auth.uid())));
create policy product_member_data on public.products for all to authenticated using (exists(select 1 from public.business_users bu where bu.business_id=products.business_id and bu.user_id=(select auth.uid()))) with check (exists(select 1 from public.business_users bu where bu.business_id=products.business_id and bu.user_id=(select auth.uid())));
-- Add equivalent membership policies for remaining tables before production launch.
