'use client';
import {useEffect,useMemo,useRef,useState} from 'react';

type Payment={id:string;date:string;amount:number;note?:string};
type Sale={id:string;date:string;client:string;description:string;amount:number;currency?:'C$'|'US$';enteredAmount?:number;status:string;paidAmount?:number;payments?:Payment[]};
type Expense={id:string;date:string;category:string;description:string;amount:number;currency?:'C$'|'US$';enteredAmount?:number};
type Account={id:string;name:string;currency:'C$'|'US$';balance:number;updated:string};
type InventoryItem={id:string;name:string;category:string;qty:number;unitValue:number;currency?:'C$'|'US$';enteredUnitValue?:number};
type InventoryClose={id:string;month:string;date:string;items:InventoryItem[];total:number;notes:string};
type MonthClose={id:string;month:string;closedAt:string;rate:number;inventoryC:number;accounts:{name:string;currency:'C$'|'US$';balance:number;equivalentC:number}[];bankCashC:number;expensesC:number;salesC:number;currentValueC:number;baseC:number;resultC:number;notes:string};
type Client={id:string;name:string;phone:string;email:string};
type Quote={id:string;date:string;client:string;description:string;amount:number;currency?:'C$'|'US$';enteredAmount?:number;status:string};
type Job={id:string;date:string;client:string;description:string;stage:string};
const tabs=['Dashboard','Ventas','Gastos','Inventario mensual','Cierre del mes','Bancos y Caja','Contabilidad','Cotizaciones','Producción','Clientes','Reportes','Configuración'];
const uid=(p:string)=>p+'-'+Date.now().toString().slice(-8);
const today=()=>new Date().toISOString().slice(0,10);
const monthNow=()=>new Date().toISOString().slice(0,7);
const money=(n:number,c:'C$'|'US$'='C$')=>`${c}${new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)}`;
const dual=(nio:number,rate:number)=>`${money(nio,'C$')} · ${money(rate>0?nio/rate:0,'US$')}`;
const toNio=(amount:number,currency:'C$'|'US$',rate:number)=>currency==='US$'?amount*rate:amount;
const useStore=<T,>(key:string,initial:T)=>{
 const [v,setV]=useState<T>(initial);
 const hydrated=useRef(false);
 useEffect(()=>{
  try{const x=localStorage.getItem(key);if(x!==null)setV(JSON.parse(x))}
  catch(e){console.error('IMPRESA: no se pudo leer '+key,e)}
  finally{hydrated.current=true}
 },[key]);
 useEffect(()=>{
  if(!hydrated.current)return;
  try{localStorage.setItem(key,JSON.stringify(v))}
  catch(e){console.error('IMPRESA: no se pudo guardar '+key,e)}
 },[key,v]);
 return [v,setV] as const
};

export default function Home(){
 const [tab,setTab]=useState('Dashboard'),[month,setMonth]=useState(monthNow()),[rate,setRate]=useStore('impresa-rate',37);
 const [sales,setSales]=useStore<Sale[]>('impresa-simple-sales',[]);
 const [expenses,setExpenses]=useStore<Expense[]>('impresa-simple-expenses',[]);
 const [accounts,setAccounts]=useStore<Account[]>('impresa-simple-accounts',[
  {id:'bac-usd',name:'BAC Dólares',currency:'US$',balance:0,updated:today()},
  {id:'bac-nio',name:'BAC Córdobas',currency:'C$',balance:0,updated:today()},
  {id:'cash',name:'Efectivo',currency:'C$',balance:0,updated:today()}
 ]);
 const [closes,setCloses]=useStore<InventoryClose[]>('impresa-simple-inventory',[]);
 const [monthCloses,setMonthCloses]=useStore<MonthClose[]>('impresa-month-closes',[]);
 const [clients,setClients]=useStore<Client[]>('impresa-simple-clients',[]);
 const [quotes,setQuotes]=useStore<Quote[]>('impresa-simple-quotes',[]);
 const [jobs,setJobs]=useStore<Job[]>('impresa-simple-jobs',[]);
 const props={sales,setSales,expenses,setExpenses,accounts,setAccounts,closes,setCloses,monthCloses,setMonthCloses,clients,setClients,quotes,setQuotes,jobs,setJobs,month,rate,setRate};
 return <div className="app"><aside><div className="brandWrap"><div className="brandMark">I</div><div><div className="brand">IMPRESA</div><div className="sub">Business Management</div></div></div><div className="workspace">OPERACIONES · NICARAGUA</div><nav>{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav></aside><main><header><div><div className="eyebrow">IMPRESA / {month}</div><h1>{tab}</h1><p>Centro administrativo y financiero del negocio</p></div><div className="actions"><label className="month"><span>Mes</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button className="btn" onClick={()=>setTab('Gastos')}>+ Gasto</button><button className="btn primary" onClick={()=>setTab('Ventas')}>+ Venta</button></div></header>
 {tab==='Dashboard'?<Dashboard {...props}/>:tab==='Ventas'?<Sales {...props}/>:tab==='Gastos'?<Expenses {...props}/>:tab==='Inventario mensual'?<Inventory {...props}/>:tab==='Cierre del mes'?<MonthClosing {...props}/>:tab==='Bancos y Caja'?<Accounts {...props}/>:tab==='Contabilidad'?<Accounting {...props}/>:tab==='Cotizaciones'?<Quotes {...props}/>:tab==='Producción'?<Production {...props}/>:tab==='Clientes'?<Clients {...props}/>:tab==='Reportes'?<Reports {...props}/>:<Settings {...props}/>}
 </main></div>
}
function Dashboard({sales,expenses,accounts,closes,monthCloses,month,rate}:any){
 const sm=sales.filter((x:Sale)=>x.date.startsWith(month)),em=expenses.filter((x:Expense)=>x.date.startsWith(month));
 const last=[...closes].sort((a:InventoryClose,b:InventoryClose)=>b.month.localeCompare(a.month))[0];
 const inventory=last?.total||0,bankCash=accounts.reduce((n:number,x:Account)=>n+(x.currency==='US$'?x.balance*rate:x.balance),0);
 const salesM=sm.reduce((n:number,x:Sale)=>n+x.amount,0),expM=em.reduce((n:number,x:Expense)=>n+x.amount,0),patrimony=inventory+bankCash;
 const expenseCats=Object.entries(em.reduce((o:any,x:Expense)=>(o[x.category]=(o[x.category]||0)+x.amount,o),{})).map(([label,value])=>({label,value:Number(value)}));
 const trend=[...monthCloses].sort((a:MonthClose,b:MonthClose)=>a.month.localeCompare(b.month)).slice(-6).map((x:MonthClose)=>({label:x.month.slice(5),value:x.currentValueC}));
 return <><section className="hero"><div><div className="eyebrow light">RESUMEN EJECUTIVO · {month}</div><h2>Estado general del negocio</h2><p>Vista consolidada de liquidez, inventario y actividad operativa.</p></div><div className="heroValue"><span>Patrimonio operativo</span><strong>{dual(patrimony,rate)}</strong></div></section>
 <div className="kpis"><Kpi icon="◈" t="Bancos y caja" v={dual(bankCash,rate)} sub="Saldo consolidado"/><Kpi icon="▦" t="Inventario" v={dual(inventory,rate)} sub={last?`Cierre ${last.month}`:'Sin cierre'}/><Kpi icon="↗" t="Ventas registradas" v={dual(salesM,rate)} sub={`${sm.length} movimientos · informativo`}/><Kpi icon="↘" t="Gastos del mes" v={dual(expM,rate)} sub={`${em.length} movimientos`}/></div>
 <div className="dashboardGrid"><Panel title="Evolución del valor del negocio"><MiniLine data={trend} moneyMode/><div className="chartLegend"><span>Últimos cierres mensuales</span><b>{trend.length?dual(trend[trend.length-1].value,rate):'Sin cierres'}</b></div></Panel><Panel title="Distribución de gastos"><MiniBars data={expenseCats} rate={rate}/>{!expenseCats.length&&<Empty text="No hay gastos registrados este mes."/>}</Panel></div>
 <div className="dashboardGrid"><Panel title="Liquidez por cuenta">{accounts.map((x:Account)=>{const c=x.currency==='US$'?x.balance*rate:x.balance;return <div className="accountRow" key={x.id}><div><b>{x.name}</b><small>{x.currency} · actualizado {x.updated}</small></div><strong>{dual(c,rate)}</strong></div>})}</Panel><Panel title="Control del período"><div className="healthList"><Health label="Inventario mensual" ok={!!last} text={last?`Último cierre: ${last.month}`:'Pendiente de registrar'}/><Health label="Cierre contable" ok={monthCloses.some((x:MonthClose)=>x.month===month)} text={monthCloses.some((x:MonthClose)=>x.month===month)?'Mes cerrado':'Mes abierto'}/><Health label="Tipo de cambio" ok={rate>0} text={`C$${rate.toFixed(2)} = US$1`}/></div></Panel></div></>
}
function Sales({sales,setSales,month,rate}:any){
 const [f,setF]=useState({date:today(),client:'',description:'',amount:'',currency:'C$',initialPayment:''});
 const entered=+f.amount||0,nio=toNio(entered,f.currency as 'C$'|'US$',rate),initialEntered=Math.max(0,+f.initialPayment||0),initialNio=Math.min(nio,toNio(initialEntered,f.currency as 'C$'|'US$',rate));
 const paid=(x:Sale)=>x.paidAmount!==undefined?x.paidAmount:(x.status==='Pagada'?x.amount:0);
 const statusFor=(total:number,p:number)=>p<=0?'Pendiente':p>=total?'Pagada':'Pago parcial';
 const add=()=>{if(!f.client||!entered)return alert('Completa cliente y monto.');if(initialEntered>entered)return alert('El pago inicial no puede ser mayor que el total de la venta.');const status=statusFor(nio,initialNio);const payments:Payment[]=initialNio>0?[{id:uid('AB'),date:f.date,amount:initialNio,note:'Pago inicial'}]:[];setSales([...sales,{id:uid('V'),date:f.date,client:f.client,description:f.description,amount:nio,currency:f.currency as 'C$'|'US$',enteredAmount:entered,status,paidAmount:initialNio,payments}]);setF({...f,client:'',description:'',amount:'',initialPayment:''})};
 const abonar=(x:Sale)=>{const current=paid(x),balance=Math.max(0,x.amount-current);if(balance<=0)return alert('Esta venta ya está pagada.');const raw=prompt(`Saldo pendiente: ${dual(balance,rate)}\nMonto del nuevo abono en C$:`,String(balance));if(raw===null)return;const amount=+raw;if(!amount||amount<=0)return alert('Ingresa un abono válido.');if(amount>balance)return alert('El abono no puede ser mayor que el saldo pendiente.');const next=current+amount;const payment:Payment={id:uid('AB'),date:today(),amount,note:'Abono'};setSales(sales.map((z:Sale)=>z.id===x.id?{...z,paidAmount:next,status:statusFor(z.amount,next),payments:[...(z.payments||[]),payment]}:z))};
 const history=(x:Sale)=>{const ps=x.payments||[];if(!ps.length)return alert('Esta venta todavía no tiene abonos registrados.');alert(`Historial de pagos · ${x.id}\n\n`+ps.map(p=>`${p.date} — ${money(p.amount,'C$')} — ${p.note||'Pago'}`).join('\n')+`\n\nPagado: ${money(paid(x),'C$')}\nSaldo: ${money(Math.max(0,x.amount-paid(x)),'C$')}`)};
 const visible=sales.filter((x:Sale)=>x.date.startsWith(month)).slice().reverse();
 const pending=visible.reduce((n:number,x:Sale)=>n+Math.max(0,x.amount-paid(x)),0);
 return <><div className="cards"><div className="card"><span>VENTAS DEL MES</span><strong>{dual(visible.reduce((n:number,x:Sale)=>n+x.amount,0),rate)}</strong></div><div className="card"><span>COBRADO</span><strong>{dual(visible.reduce((n:number,x:Sale)=>n+paid(x),0),rate)}</strong></div><div className="card"><span>CUENTAS POR COBRAR</span><strong>{dual(pending,rate)}</strong><small>Ventas pendientes y pagos parciales</small></div></div><Panel title="Registro de ventas"><div className="form grid"><Input l="Fecha" v={f.date} s={v=>setF({...f,date:v})} type="date"/><Input l="Cliente" v={f.client} s={v=>setF({...f,client:v})}/><Input l="Trabajo / descripción" v={f.description} s={v=>setF({...f,description:v})}/><Input l={`Total ${f.currency}`} v={f.amount} s={v=>setF({...f,amount:v})} type="number"/><Select l="Moneda" v={f.currency} s={v=>setF({...f,currency:v})} opts={['C$','US$']}/><Input l={`Pago inicial ${f.currency}`} v={f.initialPayment} s={v=>setF({...f,initialPayment:v})} type="number"/><div className="conversion"><span>Estado automático</span><b>{statusFor(nio,initialNio)} · Saldo {dual(Math.max(0,nio-initialNio),rate)}</b></div><button className="btn primary" onClick={add}>Registrar venta</button></div><Table heads={['Fecha','Cliente','Trabajo','Total','Pagado','Saldo','Estado','Acciones']} rowClasses={visible.map((x:Sale)=>Math.max(0,x.amount-paid(x))>0?'salePending':'')} rows={visible.map((x:Sale)=>{const p=paid(x),bal=Math.max(0,x.amount-p);return [x.date,x.client,x.description||'—',money(x.amount,'C$'),money(p,'C$'),money(bal,'C$'),x.status,<div className="actions"><button className="small" disabled={bal<=0} onClick={()=>abonar(x)}>+ Abono</button><button className="small" onClick={()=>history(x)}>Historial</button><button className="dangerSmall" onClick={()=>{if(confirm('¿Borrar esta venta y su historial de pagos?'))setSales(sales.filter((z:Sale)=>z.id!==x.id))}}>Borrar</button></div>]})}/><div className="note">El estado ya no se selecciona manualmente: 0 pagado = Pendiente; un abono menor al total = Pago parcial; saldo C$0 = Pagada. Los abonos quedan guardados con la venta.</div></Panel></>}

function Expenses({expenses,setExpenses,month,rate}:any){const [f,setF]=useState({date:today(),category:'Operativo',description:'',amount:'',currency:'C$'});const entered=+f.amount||0,nio=toNio(entered,f.currency as 'C$'|'US$',rate);const add=()=>{if(!f.description||!entered)return alert('Completa descripción y monto.');setExpenses([...expenses,{id:uid('G'),date:f.date,category:f.category,description:f.description,amount:nio,currency:f.currency as 'C$'|'US$',enteredAmount:entered}]);setF({...f,description:'',amount:''})};return <Panel title="Registro de gastos"><div className="form grid"><Input l="Fecha" v={f.date} s={v=>setF({...f,date:v})} type="date"/><Select l="Categoría" v={f.category} s={v=>setF({...f,category:v})} opts={['Materiales','Operativo','Servicios','Transporte','Nómina','Publicidad','Equipos','Otro']}/><Input l="Descripción" v={f.description} s={v=>setF({...f,description:v})}/><Input l={`Monto ${f.currency}`} v={f.amount} s={v=>setF({...f,amount:v})} type="number"/><Select l="Moneda" v={f.currency} s={v=>setF({...f,currency:v})} opts={['C$','US$']}/><div className="conversion"><span>Conversión automática</span><b>{dual(nio,rate)}</b></div><button className="btn primary" onClick={add}>Guardar gasto</button></div><Table heads={['Fecha','Categoría','Descripción','C$','US$','Acción']} rows={expenses.filter((x:Expense)=>x.date.startsWith(month)).slice().reverse().map((x:Expense)=>[x.date,x.category,x.description,money(x.amount,'C$'),money(rate>0?x.amount/rate:0,'US$'),<button className="dangerSmall" onClick={()=>{if(confirm('¿Borrar este gasto?'))setExpenses(expenses.filter((z:Expense)=>z.id!==x.id))}}>Borrar</button>])}/></Panel>}
function Accounts({accounts,setAccounts,rate}:any){const [f,setF]=useState({name:'',currency:'C$'});const add=()=>{if(!f.name)return;setAccounts([...accounts,{id:uid('CTA'),name:f.name,currency:f.currency as 'C$'|'US$',balance:0,updated:today()}]);setF({...f,name:''})};const update=(a:Account)=>{const x=prompt(`Saldo actual de ${a.name} (${a.currency})`,String(a.balance));if(x===null||isNaN(+x))return;setAccounts(accounts.map((z:Account)=>z.id===a.id?{...z,balance:+x,updated:today()}:z))};return <><div className="cards">{accounts.map((a:Account)=>{const nio=a.currency==='US$'?a.balance*rate:a.balance;return <div className="card account" key={a.id}><span>{a.name} · {a.currency}</span><strong>{money(a.balance,a.currency)}</strong><small>{dual(nio,rate)} · Actualizado {a.updated}</small><div className="actions"><button className="small" onClick={()=>update(a)}>Actualizar saldo</button><button className="dangerSmall" onClick={()=>{if(confirm(`¿Borrar la cuenta ${a.name}?`))setAccounts(accounts.filter((z:Account)=>z.id!==a.id))}}>Borrar</button></div></div>})}</div><Panel title="Agregar cuenta o caja"><div className="form inline"><Input l="Nombre (ej. BAC Dólares)" v={f.name} s={v=>setF({...f,name:v})}/><Select l="Moneda" v={f.currency} s={v=>setF({...f,currency:v})} opts={['C$','US$']}/><button className="btn primary" onClick={add}>Agregar cuenta</button></div><div className="note">Tipo de cambio actual del sistema: C${rate.toFixed(2)} = US$1.00. El resumen convierte automáticamente todas las cuentas.</div></Panel></>}
function Inventory({closes,setCloses,monthCloses,setMonthCloses,sales,expenses,accounts,month,rate}:any){
 const existing=[...closes].reverse().find((x:InventoryClose)=>x.month===month);
 const [items,setItems]=useState<InventoryItem[]>(existing?.items||[]),[f,setF]=useState({name:'',category:'Camisas',qty:'',unitValue:'',currency:'C$'}),[notes,setNotes]=useState(existing?.notes||'');
 const total=items.reduce((a,x)=>a+x.qty*x.unitValue,0),entered=+f.unitValue||0,unitNio=toNio(entered,f.currency as 'C$'|'US$',rate),closed=monthCloses.some((x:MonthClose)=>x.month===month);
 const add=()=>{if(closed)return alert('Este mes ya está cerrado.');if(!f.name||!+f.qty)return alert('Completa producto/material y cantidad.');setItems([...items,{id:uid('I'),name:f.name,category:f.category,qty:+f.qty,unitValue:unitNio,currency:f.currency as 'C$'|'US$',enteredUnitValue:entered}]);setF({...f,name:'',qty:'',unitValue:''})};
 const save=()=>{if(closed)return alert('Este mes ya está cerrado.');if(!items.length)return alert('Agrega al menos un producto o material.');const rec:InventoryClose={id:existing?.id||uid('INV'),month,date:today(),items:[...items],total,notes};setCloses([...closes.filter((x:InventoryClose)=>x.month!==month),rec]);alert(`Inventario ${month} guardado correctamente.`)};
 return <><div className="cols"><Panel title={`Conteo de inventario · ${month}`}>{closed?<div className="closedBanner">✓ Este mes está CERRADO.</div>:<><div className="form grid"><Input l="Producto / material" v={f.name} s={v=>setF({...f,name:v})}/><Select l="Categoría" v={f.category} s={v=>setF({...f,category:v})} opts={['Camisas','Hilos','Tintas','Vinil','Sublimación','Empaque','Otros']}/><Input l="Cantidad física" v={f.qty} s={v=>setF({...f,qty:v})} type="number"/><Input l={`Valor unitario ${f.currency}`} v={f.unitValue} s={v=>setF({...f,unitValue:v})} type="number"/><Select l="Moneda" v={f.currency} s={v=>setF({...f,currency:v})} opts={['C$','US$']}/><div className="conversion"><span>Valor unitario convertido</span><b>{dual(unitNio,rate)}</b></div><button className="btn" onClick={add}>+ Agregar al conteo</button></div><Table heads={['Producto/material','Categoría','Cantidad','Unit. C$','Unit. US$','Total C$','Total US$','Acción']} rows={items.map(x=>[x.name,x.category,x.qty,money(x.unitValue,'C$'),money(rate>0?x.unitValue/rate:0,'US$'),money(x.qty*x.unitValue,'C$'),money(rate>0?x.qty*x.unitValue/rate:0,'US$'),<button className="dangerSmall" onClick={()=>setItems(items.filter(z=>z.id!==x.id))}>Borrar</button>])}/></>}</Panel><Panel title="Guardar inventario"><Stat l="Líneas contadas" v={String(items.length)}/><Stat l="Valor total C$" v={money(total,'C$')}/><Stat l="Valor total US$" v={money(rate>0?total/rate:0,'US$')}/><label><span>Notas</span><textarea disabled={closed} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="btn primary wide" disabled={closed} onClick={save}>{closed?'Mes cerrado':'Guardar inventario'}</button><p className="muted">Guardar no cierra el mes. El cierre definitivo está en “Cierre del mes”.</p></Panel></div><Panel title="Historial de inventarios"><Table heads={['Mes','Fecha','Productos/materiales','Total C$','Total US$','Notas','Acción']} rows={[...closes].sort((a:InventoryClose,b:InventoryClose)=>b.month.localeCompare(a.month)).map((x:InventoryClose)=>[x.month,x.date,x.items.length,money(x.total,'C$'),money(rate>0?x.total/rate:0,'US$'),x.notes,<button className="dangerSmall" onClick={()=>{if(confirm(`¿Borrar el inventario de ${x.month}?`))setCloses(closes.filter((z:InventoryClose)=>z.id!==x.id))}}>Borrar</button>])}/></Panel></>
}
function MonthClosing({closes,monthCloses,setMonthCloses,sales,expenses,accounts,month,rate}:any){
 const inv=[...closes].reverse().find((x:InventoryClose)=>x.month===month),closed=monthCloses.find((x:MonthClose)=>x.month===month),previous=[...monthCloses].filter((x:MonthClose)=>x.month<month).sort((a:MonthClose,b:MonthClose)=>b.month.localeCompare(a.month))[0];
 const inventoryC=inv?.total||0,bankRows=accounts.map((a:Account)=>({name:a.name,currency:a.currency,balance:a.balance,equivalentC:a.currency==='US$'?a.balance*rate:a.balance})),bankCashC=bankRows.reduce((n:number,a:any)=>n+a.equivalentC,0),expensesC=expenses.filter((x:Expense)=>x.date.startsWith(month)).reduce((n:number,x:Expense)=>n+x.amount,0),salesC=sales.filter((x:Sale)=>x.date.startsWith(month)).reduce((n:number,x:Sale)=>n+x.amount,0);
 const currentValueC=inventoryC+bankCashC,baseC=4100*rate,resultC=currentValueC-baseC;
 const close=()=>{if(closed)return alert('Este mes ya está cerrado.');if(!inv)return alert('Primero guarda el inventario del mes.');if(!confirm(`¿Cerrar definitivamente ${month}?`))return;setMonthCloses([...monthCloses,{id:uid('CIERRE'),month,closedAt:today(),rate,inventoryC,accounts:bankRows,bankCashC,expensesC,salesC,currentValueC,baseC,resultC,notes:inv.notes||''}]);alert(`${month} cerrado y guardado en Contabilidad.`)};
 return <div className="cols"><Panel title={`Cierre del mes · ${month}`}><Stat l="Inventario guardado" v={inv?dual(inventoryC,rate):'Pendiente'}/><Stat l="Bancos + caja" v={dual(bankCashC,rate)}/><Stat l="Gastos del mes" v={dual(expensesC,rate)}/><Stat l="Ventas del mes (registro)" v={dual(salesC,rate)}/><Stat l="Valor real del negocio" v={dual(currentValueC,rate)}/><Stat l="Resultado del período" v={previous?dual(resultC,rate):'C$0.00 · US$0.00 (primer cierre)'}/></Panel><Panel title="Confirmar cierre">{closed?<div className="closedBanner">✓ Mes CERRADO y guardado en Contabilidad.</div>:<><p className="muted">Primero guarda el inventario. El cierre congela inventario, bancos/caja, gastos, ventas informativas y tipo de cambio.</p><button className="btn primary wide" disabled={!inv} onClick={close}>Cerrar mes y guardar en Contabilidad</button></>}</Panel></div>
}

function Accounting({sales,expenses,accounts,closes,monthCloses,month,rate}:any){
 const selected=monthCloses.find((x:MonthClose)=>x.month===month);
 const inv=[...closes].reverse().find((x:InventoryClose)=>x.month===month)||[...closes].sort((a:InventoryClose,b:InventoryClose)=>b.month.localeCompare(a.month))[0];
 const useRate=selected?.rate??rate;
 const inventory=selected?.inventoryC??inv?.total??0;
 const liquidity=selected?.bankCashC??accounts.reduce((n:number,a:Account)=>n+(a.currency==='US$'?a.balance*useRate:a.balance),0);
 const salesInfo=selected?.salesC??sales.filter((x:Sale)=>x.date.startsWith(month)).reduce((n:number,x:Sale)=>n+x.amount,0);
 const expensesInfo=selected?.expensesC??expenses.filter((x:Expense)=>x.date.startsWith(month)).reduce((n:number,x:Expense)=>n+x.amount,0);
 const currentValue=inventory+liquidity;
 const initialUSD=4100,initialC=initialUSD*useRate;
 const gainLossC=currentValue-initialC,gainLossUSD=useRate>0?gainLossC/useRate:0;
 const pct=initialC>0?gainLossC/initialC*100:0;
 const history=[...monthCloses].sort((a:MonthClose,b:MonthClose)=>a.month.localeCompare(b.month)).slice(-8).map((x:MonthClose)=>({label:x.month.slice(5),value:x.inventoryC+x.bankCashC}));
 const expenseCats=Object.entries(expenses.filter((x:Expense)=>x.date.startsWith(month)).reduce((o:any,x:Expense)=>(o[x.category]=(o[x.category]||0)+x.amount,o),{})).map(([label,value])=>({label,value:Number(value)}));
 return <><div className="accountingHead"><div><div className="eyebrow">CENTRO FINANCIERO</div><h2>Contabilidad del negocio</h2><p>El valor real se calcula únicamente con Inventario + Bancos + Efectivo.</p></div><span className={`statusPill ${selected?'closed':'open'}`}>{selected?'● PERÍODO CERRADO':'● PERÍODO ABIERTO'}</span></div>
 <div className="kpis finance"><Kpi icon="▦" t="Inventario" v={dual(inventory,useRate)} sub="Inventario guardado"/><Kpi icon="●" t="Bancos + Efectivo" v={dual(liquidity,useRate)} sub="Liquidez real"/><Kpi icon="◆" t="Valor actual del negocio" v={dual(currentValue,useRate)} sub="Inventario + Bancos + Efectivo"/><Kpi icon={gainLossC>=0?'↗':'↘'} t="Ganancia / Pérdida" v={`${gainLossC>=0?'+':''}${dual(gainLossC,useRate)}`} sub={`${pct>=0?'+':''}${pct.toFixed(1)}% sobre capital inicial`}/></div>
 <div className="statementGrid"><Panel title="Ejercicio de ganancia / pérdida"><div className="capitalCompare"><div><span>Capital inicial histórico</span><strong>{money(initialUSD,'US$')}</strong><small>{money(initialC,'C$')}</small></div><b>→</b><div><span>Valor actual del negocio</span><strong>{money(useRate?currentValue/useRate:0,'US$')}</strong><small>{money(currentValue,'C$')}</small></div></div><div className={`bigResult ${gainLossC<0?'loss':''}`}><span>{gainLossC>0?'GANANCIA DESDE EL INICIO':gainLossC<0?'PÉRDIDA DESDE EL INICIO':'EN EL CAPITAL INICIAL'}</span><strong>{gainLossC>=0?'+':''}{money(gainLossC,'C$')} · {gainLossUSD>=0?'+':''}{money(gainLossUSD,'US$')}</strong><small>{pct>=0?'+':''}{pct.toFixed(1)}% respecto a US$4,100</small></div><div className="equationPro"><span>{dual(inventory,useRate)} <small>Inventario</small></span><b>+</b><span>{dual(liquidity,useRate)} <small>Bancos + Efectivo</small></span><b>=</b><span>{dual(currentValue,useRate)} <small>Valor actual</small></span></div></Panel>
 <Panel title="Composición del valor actual"><Donut a={liquidity} b={inventory}/><div className="donutLegend"><span><i className="dot cash"/>Bancos + Efectivo <b>{currentValue?Math.round(liquidity/currentValue*100):0}%</b></span><span><i className="dot inv"/>Inventario <b>{currentValue?Math.round(inventory/currentValue*100):0}%</b></span></div></Panel></div>
 <div className="dashboardGrid"><Panel title="Evolución del valor del negocio"><MiniLine data={history} moneyMode/><div className="chartLegend"><span>Capital inicial: {money(initialC,'C$')} · {money(initialUSD,'US$')}</span><b>Actual: {dual(currentValue,useRate)}</b></div>{!history.length&&<Empty text="El gráfico histórico aparecerá después del primer cierre mensual."/>}</Panel><Panel title="Registros informativos del mes"><div className="recordCards"><div><span>Ventas registradas</span><b>{dual(salesInfo,useRate)}</b><small>No modifica el valor del negocio</small></div><div><span>Gastos registrados</span><b>{dual(expensesInfo,useRate)}</b><small>No modifica el valor del negocio</small></div></div><p className="muted">Ventas y gastos permanecen disponibles para consulta y reportes, pero quedan fuera del cálculo de ganancia/pérdida solicitado.</p></Panel></div>
 <div className="statementGrid"><Panel title="Estado de situación del negocio"><div className="statement"><div className="statementTitle">VALOR REAL</div><Stat l="Bancos + Efectivo" v={dual(liquidity,useRate)}/><Stat l="Inventario" v={dual(inventory,useRate)}/><div className="statementTotal"><span>Valor actual total</span><b>{dual(currentValue,useRate)}</b></div><div className="statementTitle gap">CAPITAL Y RESULTADO</div><Stat l="Capital inicial histórico" v={`${money(initialC,'C$')} · ${money(initialUSD,'US$')}`}/><div className={`statementTotal result ${gainLossC<0?'loss':''}`}><span>Ganancia / Pérdida acumulada</span><b>{gainLossC>=0?'+':''}{dual(gainLossC,useRate)}</b></div></div></Panel><Panel title="Fórmula oficial de IMPRESA"><div className="formulaOfficial"><b>Inventario + Bancos + Efectivo</b><span>= Valor actual del negocio</span><hr/><b>Valor actual − Capital inicial US$4,100</b><span>= Ganancia o Pérdida</span></div><div className="infoStrip">Ventas y gastos son registros informativos. No entran en estas dos fórmulas.</div></Panel></div>
 <Panel title="Historial contable mensual"><Table heads={['Período','Inventario C$ / US$','Bancos + Efectivo C$ / US$','Valor actual C$ / US$','Capital inicial C$ / US$','Ganancia/Pérdida C$ / US$']} rows={[...monthCloses].sort((a:MonthClose,b:MonthClose)=>b.month.localeCompare(a.month)).map((x:MonthClose)=>{const r=x.rate||useRate,total=x.inventoryC+x.bankCashC,base=4100*r,diff=total-base;return [x.month,dual(x.inventoryC,r),dual(x.bankCashC,r),dual(total,r),`${money(base,'C$')} · ${money(4100,'US$')}`,`${diff>=0?'+':''}${dual(diff,r)}`]})}/></Panel></>
}
function Quotes({quotes,setQuotes,jobs,setJobs,rate}:any){const [f,setF]=useState({client:'',description:'',amount:'',currency:'C$'});const entered=+f.amount||0,nio=toNio(entered,f.currency as 'C$'|'US$',rate);const add=()=>{if(!f.client||!entered)return;setQuotes([...quotes,{id:uid('COT'),date:today(),client:f.client,description:f.description,amount:nio,currency:f.currency as 'C$'|'US$',enteredAmount:entered,status:'Borrador'}]);setF({client:'',description:'',amount:'',currency:'C$'})};const approve=(q:Quote)=>{setQuotes(quotes.map((x:Quote)=>x.id===q.id?{...x,status:'Aprobada'}:x));if(!jobs.some((j:Job)=>j.id==='P-'+q.id))setJobs([...jobs,{id:'P-'+q.id,date:today(),client:q.client,description:q.description,stage:'Nueva'}])};return <Panel title="Cotizaciones"><div className="form grid"><Input l="Cliente" v={f.client} s={v=>setF({...f,client:v})}/><Input l="Trabajo" v={f.description} s={v=>setF({...f,description:v})}/><Input l={`Total ${f.currency}`} v={f.amount} s={v=>setF({...f,amount:v})} type="number"/><Select l="Moneda" v={f.currency} s={v=>setF({...f,currency:v})} opts={['C$','US$']}/><div className="conversion"><span>Conversión automática</span><b>{dual(nio,rate)}</b></div><button className="btn primary" onClick={add}>Crear cotización</button></div><Table heads={['Nº','Cliente','Trabajo','C$','US$','Estado','Acción']} rows={quotes.slice().reverse().map((q:Quote)=>[q.id,q.client,q.description,money(q.amount,'C$'),money(rate>0?q.amount/rate:0,'US$'),q.status,<div className="actions">{q.status==='Borrador'?<button className="small" onClick={()=>approve(q)}>Aprobar → Producción</button>:null}<button className="dangerSmall" onClick={()=>{if(confirm('¿Borrar esta cotización?'))setQuotes(quotes.filter((z:Quote)=>z.id!==q.id))}}>Borrar</button></div>])}/></Panel>}
function Production({jobs,setJobs}:any){const stages=['Nueva','Diseño','Impresión','Bordado','Lista','Entregada'];const next=(j:Job)=>{const i=stages.indexOf(j.stage);if(i<stages.length-1)setJobs(jobs.map((x:Job)=>x.id===j.id?{...x,stage:stages[i+1]}:x))};return <div className="kanban">{stages.map(s=><section key={s}><h3>{s}<b>{jobs.filter((j:Job)=>j.stage===s).length}</b></h3>{jobs.filter((j:Job)=>j.stage===s).map((j:Job)=><article key={j.id}><strong>{j.client}</strong><p>{j.description}</p>{s!=='Entregada'&&<button className="small" onClick={()=>next(j)}>Siguiente →</button>}</article>)}</section>)}</div>}
function Clients({clients,setClients}:any){const [f,setF]=useState({name:'',phone:'',email:''});const add=()=>{if(!f.name)return;setClients([...clients,{id:uid('CLI'),...f}]);setF({name:'',phone:'',email:''})};return <Panel title="Clientes"><div className="form grid"><Input l="Nombre" v={f.name} s={v=>setF({...f,name:v})}/><Input l="Teléfono" v={f.phone} s={v=>setF({...f,phone:v})}/><Input l="Correo" v={f.email} s={v=>setF({...f,email:v})}/><button className="btn primary" onClick={add}>Agregar cliente</button></div><Table heads={['Cliente','Teléfono','Correo']} rows={clients.map((x:Client)=>[x.name,x.phone,x.email])}/></Panel>}
function Reports({sales,expenses,closes,accounts,rate}:any){const months=Array.from(new Set([...sales.map((x:Sale)=>x.date.slice(0,7)),...expenses.map((x:Expense)=>x.date.slice(0,7)),...closes.map((x:InventoryClose)=>x.month)])).sort().reverse();return <Panel title="Resumen por mes"><Table heads={['Mes','Ventas','Gastos','Diferencia','Inventario cierre']} rows={months.map((m:any)=>{const s=sales.filter((x:Sale)=>x.date.startsWith(m)).reduce((a:number,x:Sale)=>a+x.amount,0),e=expenses.filter((x:Expense)=>x.date.startsWith(m)).reduce((a:number,x:Expense)=>a+x.amount,0),i=[...closes].reverse().find((x:InventoryClose)=>x.month===m);return [m,money(s),money(e),money(s-e),money(i?.total||0)]})}/></Panel>}
function Settings({rate,setRate}:any){const initialNio=4100*rate;return <div className="cols"><Panel title="Regla del Resultado del Negocio"><div className="equation">Inventario + Bancos/Caja − Gastos = Valor actual</div><div className="equation second">Valor actual − Base histórica = Ganancia / Pérdida</div><p className="muted">Puedes registrar cada monto en C$ o US$. El sistema guarda el equivalente automáticamente usando el tipo de cambio configurado. Las ventas son solo registro y no se suman al resultado.</p></Panel><Panel title="Configuración"><Input l="Tipo de cambio: C$ por US$1" v={String(rate)} s={v=>setRate(+v||0)} type="number"/><Stat l="Capital inicial histórico" v={money(4100,'US$')}/><Stat l="Equivalente de referencia" v={money(initialNio,'C$')}/><Stat l="Moneda principal" v="C$"/></Panel></div>}
function Kpi({icon,t,v,sub}:any){return <div className="kpi"><div className="kpiIcon">{icon}</div><div><span>{t}</span><strong>{v}</strong><small>{sub}</small></div></div>}
function Health({label,ok,text}:any){return <div className="health"><i className={ok?'ok':'wait'}>{ok?'✓':'!'}</i><div><b>{label}</b><span>{text}</span></div></div>}
function MiniLine({data,moneyMode}:any){if(!data?.length)return null;const max=Math.max(...data.map((x:any)=>x.value),1),min=Math.min(...data.map((x:any)=>x.value),0),range=Math.max(max-min,1);const pts=data.map((x:any,i:number)=>`${data.length===1?50:i/(data.length-1)*100},${92-((x.value-min)/range)*72}`).join(' ');return <div className="lineChart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".22"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${pts} 100,100`} fill="url(#area)"/><polyline points={pts} fill="none" vectorEffect="non-scaling-stroke"/></svg><div className="chartLabels">{data.map((x:any)=><span key={x.label}>{x.label}</span>)}</div></div>}
function MiniBars({data,rate}:any){if(!data?.length)return null;const max=Math.max(...data.map((x:any)=>x.value),1);return <div className="barChart">{data.slice(0,6).map((x:any)=><div className="barRow" key={x.label}><span>{x.label}</span><div><i style={{width:`${Math.max(3,x.value/max*100)}%`}}/></div><b>{rate?dual(x.value,rate):money(x.value,'C$')}</b></div>)}</div>}
function Donut({a,b}:any){const total=a+b,p=total?a/total*100:0;return <div className="donutWrap"><div className="donut" style={{background:`conic-gradient(#3157d5 0 ${p}%, #12a594 ${p}% 100%)`}}><div><strong>{money(total,'C$')}</strong><span>Activos</span></div></div></div>}

function Card({t,v}:{t:string;v:string}){return <div className="card"><span>{t}</span><strong>{v}</strong></div>}
function Panel({title,children}:{title:string;children:any}){return <div className="panel"><h2>{title}</h2>{children}</div>}
function Stat({l,v}:{l:string;v:string}){return <div className="stat"><span>{l}</span><b>{v}</b></div>}
function Input({l,v,s,type='text'}:{l:string;v:string;s:(v:string)=>void;type?:string}){return <label><span>{l}</span><input type={type} value={v} onChange={e=>s(e.target.value)}/></label>}
function Select({l,v,s,opts}:{l:string;v:string;s:(v:string)=>void;opts:string[]}){return <label><span>{l}</span><select value={v} onChange={e=>s(e.target.value)}>{opts.map(x=><option value={x} key={x}>{x}</option>)}</select></label>}
function Table({heads,rows,rowClasses=[]}:{heads:string[];rows:any[][];rowClasses?:string[]}){return <div className="tablewrap"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className={rowClasses[i]||''}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
function Empty({text='No hay registros.'}:{text?:string}){return <div className="empty">{text}</div>}
