'use client';
import {useRef,useState} from 'react';
import type {ReactNode,FormEvent} from 'react';
import type {Sale,SaleLine,Expense,Currency,PaymentMethod,InventoryClose,InventoryItem} from '../lib/db';
import {uid} from '../lib/db';
import ManagedSelect from './ManagedSelect';

type Setter<T>=(items:T[])=>void|Promise<void>;
type SalesProps={sales:Sale[];setSales:Setter<Sale>;accounts?:any[];setAccounts?:Setter<any>;month:string;rate:number;paymentMethods?:string[];addPaymentMethod?:(name:string)=>Promise<void>;removePaymentMethod?:(name:string)=>Promise<void>;closes?:InventoryClose[];reloadInventory?:()=>void};
const today=()=>new Date().toISOString().slice(0,10);
const money=(n:number)=>'C$'+n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const dual=(n:number,rate:number)=>`${money(n)} · US$${(rate>0?n/rate:0).toFixed(2)}`;
const paid=(sale:Sale)=>sale.paidAmount??(sale.status==='Pagada'?sale.amount:0);
const status=(total:number,value:number)=>value<=0?'Pendiente':value>=total?'Pagada':'Pago parcial';
const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
const convert=(value:string,currency:Currency,rate:number)=>round(Number(value)*(currency==='US$'?rate:1));
// Muestra el mensaje del error si trae uno útil (por ejemplo, avisando qué migración de Supabase falta correr); si no, el mensaje genérico.
const errMsg=(err:unknown,fallback:string)=>(err instanceof Error&&err.message)?err.message:fallback;
const DEFAULT_METHODS:PaymentMethod[]=['Transferencia','Efectivo'];
function Field({label,children}:{label:ReactNode;children:ReactNode}){return <label><span>{label}</span>{children}</label>}
function Method({value,onChange,methods,onAdd,onRemove,allowEmpty=false}:{value:string;onChange:(v:PaymentMethod)=>void;methods:string[];onAdd?:()=>void;onRemove?:(name:string)=>void|Promise<void>;allowEmpty?:boolean}){
 const label=onAdd?<>Método de pago <button type="button" className="addChip" onClick={onAdd} title="Agregar método de pago">+</button></>:'Método de pago';
 return <Field label={label}><ManagedSelect value={value} onChange={v=>onChange(v as PaymentMethod)} options={methods} emptyLabel={allowEmpty?'Selecciona un método':undefined} onRemove={onRemove} confirmMessage={(m:string)=>`¿Borrar "${m}" de tu lista de métodos de pago? Las ventas que ya tienen este método conservan el dato; solo deja de aparecer para ventas nuevas.`}/></Field>
}
function CurrencyField({value,onChange}:{value:Currency;onChange:(v:Currency)=>void}){return <Field label="Moneda"><select value={value} onChange={e=>onChange(e.target.value as Currency)}><option>C$</option><option>US$</option></select></Field>}
function GridTable({heads,children}:{heads:string[];children:ReactNode}){return <div className="tablewrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Message({text,error}:{text:string;error:boolean}){return text?<p role={error?'alert':'status'} className={'inlineMessage'+(error?' error':'')}>{text}</p>:null}
function methodClass(method?:string){return !method?'unclassified':method==='Transferencia'?'transfer':method==='Efectivo'?'cash':'other'}
function MethodBadge({method}:{method?:string}){return <span className={'methodBadge '+methodClass(method)}>{method||'Sin clasificar'}</span>}

export function Sales({sales,setSales,accounts=[],setAccounts,month,rate,closes=[],reloadInventory}:SalesProps){
 const accountList=accounts as any[];
 const inventory=(closes.find(c=>c.month===month)?.items||[]) as InventoryItem[];
 const blankLine=():SaleLine=>({id:uid(),mode:'inventory',name:'',talla:'',color:'',quantity:1,unitPrice:0});
 const empty=()=>({date:today(),client:'',description:'',currency:'C$' as Currency,initialPayment:'',paymentAccountId:'',lines:[blankLine()]});
 const [f,setF]=useState(empty),[editing,setEditing]=useState<Sale|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
 const [paymentSale,setPaymentSale]=useState<string|null>(null),[paymentAmount,setPaymentAmount]=useState(''),[paymentAccountId,setPaymentAccountId]=useState(''),[paymentDate,setPaymentDate]=useState(today),[historyId,setHistoryId]=useState<string|null>(null);
 const editor=useRef<HTMLDivElement>(null),paymentEditor=useRef<HTMLDivElement>(null);
 const visible=sales.filter(s=>s.date.startsWith(month)).slice().sort((a,b)=>b.date.localeCompare(a.date));
 const totalSalesC=visible.reduce((n,s)=>n+(Number(s.amount)||0),0); const collectedSalesC=visible.reduce((n,s)=>n+Math.min(Number(s.amount)||0,paid(s)),0); const pendingSalesC=Math.max(0,totalSalesC-collectedSalesC);
 const lineTotal=(l:SaleLine)=>Math.max(0,Number(l.quantity)||0)*Math.max(0,Number(l.unitPrice)||0);
 const enteredTotal=f.lines.reduce((n,l)=>n+lineTotal(l),0); const total=convert(String(enteredTotal),f.currency,rate);
 const notify=(text:string,isError=false)=>{setMessage(text);setError(isError)};
 const setLine=(id:string,patch:Partial<SaleLine>)=>setF(prev=>({...prev,lines:prev.lines.map(l=>l.id===id?{...l,...patch}:l)}));
 const pickInventory=(lineId:string,itemId:string)=>{const p=inventory.find(x=>x.id===itemId);if(!p)return;const unitPrice=p.currency==='US$'?(p.enteredUnitValue??p.unitValue/rate):(p.enteredUnitValue??p.unitValue);setLine(lineId,{mode:'inventory',inventoryItemId:p.id,productCode:p.sku,name:p.name,category:p.category,talla:p.talla||'',color:p.color||'',quantity:1,unitPrice:round(unitPrice)});};
 const addManual=(id:string)=>setLine(id,{mode:'manual',inventoryItemId:undefined,productCode:'',name:'',category:'Servicio',talla:'',color:'',quantity:1,unitPrice:0});
 const addLine=()=>setF(prev=>({...prev,lines:[...prev.lines,blankLine()]})); const removeLine=(id:string)=>setF(prev=>({...prev,lines:prev.lines.length>1?prev.lines.filter(l=>l.id!==id):prev.lines}));
 const reset=()=>{setEditing(null);setF(empty())};
 const edit=(sale:Sale)=>{const fallback:SaleLine[]=[{id:uid(),mode:sale.inventoryItemId?'inventory':'manual',inventoryItemId:sale.inventoryItemId,productCode:sale.productCode,name:sale.productName||sale.description||'',category:sale.productCategory,talla:sale.talla||'',color:sale.color||'',quantity:sale.quantity||1,unitPrice:round((sale.enteredAmount??sale.amount/(sale.currency==='US$'?rate:1))/(sale.quantity||1))}];setEditing(sale);setF({date:sale.date,client:sale.client,description:sale.description,currency:sale.currency||'C$',initialPayment:'',paymentAccountId:sale.payments?.[0]?.accountId||'',lines:sale.lineItems?.length?sale.lineItems:fallback});setMessage('');editor.current?.scrollIntoView({behavior:'smooth'})};
 const accountAmount=(amountC:number,account:any)=>account?.currency==='US$'?(rate>0?amountC/rate:0):amountC;
 const applyAccountCredit=(accountId:string,amountC:number,direction:1|-1=1)=>{if(!setAccounts||!accountId)return;setAccounts(accountList.map(a=>a.id===accountId?{...a,balance:round((Number(a.balance)||0)+direction*accountAmount(amountC,a)),updated:today()}:a));};
 const save=async(e:FormEvent)=>{e.preventDefault();if(busy)return;const initial=editing?paid(editing):convert(f.initialPayment||'0',f.currency,rate);const payAccount=accountList.find(a=>a.id===f.paymentAccountId);if(!f.date||!f.client.trim()||!f.lines.length||enteredTotal<=0)return notify('Completa fecha, cliente y agrega al menos un producto o servicio con precio.',true);for(const l of f.lines){if(!l.name.trim()||l.quantity<=0||l.unitPrice<0)return notify('Revisa producto, cantidad y precio de cada línea.',true);if(l.mode==='inventory'){const inv=inventory.find(x=>x.id===l.inventoryItemId);const old=(editing?.lineItems||[]).filter(x=>x.inventoryItemId===l.inventoryItemId).reduce((n,x)=>n+x.quantity,0);if(!inv||l.quantity>inv.qty+old)return notify(`Inventario insuficiente para ${l.name}. Disponible: ${(inv?.qty||0)+old}.`,true)}}if(initial<0||initial>total)return notify('El pago inicial no puede superar el total.',true);if(!editing&&initial>0&&!payAccount)return notify('Selecciona la cuenta de Banco y Efectivo donde entró el pago inicial.',true);
 const firstInv=f.lines.find(l=>l.mode==='inventory');const initialPayment=!editing&&initial>0&&payAccount?{id:uid(),date:f.date,amount:initial,method:payAccount.name,accountId:payAccount.id,accountName:payAccount.name,note:'Pago inicial'}:null;const sale:Sale={...(editing||{id:uid()}),date:f.date,client:f.client.trim(),description:f.description.trim()||f.lines.map(l=>`${l.quantity} ${l.name}${l.talla?' '+l.talla:''}`).join(', '),amount:total,currency:f.currency,enteredAmount:enteredTotal,paymentMethod:editing?.paymentMethod||(payAccount?.name||undefined),lineItems:f.lines,inventoryItemId:firstInv?.inventoryItemId,productCode:firstInv?.productCode,productName:f.lines.length===1?f.lines[0].name:`${f.lines.length} artículos/servicios`,productCategory:firstInv?.category,talla:f.lines.length===1?f.lines[0].talla:undefined,color:f.lines.length===1?f.lines[0].color:undefined,quantity:f.lines.length===1?f.lines[0].quantity:undefined,status:status(total,initial),paidAmount:initial,payments:editing?.payments||(initialPayment?[initialPayment]:[])};
 setBusy(true);try{await setSales(editing?sales.map(s=>s.id===editing.id?sale:s):[...sales,sale]);if(initialPayment)applyAccountCredit(initialPayment.accountId!,initialPayment.amount,1);await reloadInventory?.();notify(editing?'Venta actualizada e inventario recalculado.':'Venta registrada: inventario descontado y pago enviado a la cuenta seleccionada.');reset()}catch(err){notify(errMsg(err,'No se pudo guardar la venta.'),true)}finally{setBusy(false)}};
 const addPayment=async(e:FormEvent)=>{e.preventDefault();const sale=sales.find(s=>s.id===paymentSale);if(!sale||busy)return;const amount=round(Number(paymentAmount)),balance=round(sale.amount-paid(sale));const acct=accountList.find(a=>a.id===paymentAccountId);if(!paymentDate||amount<=0||amount>balance)return notify('El abono no puede superar el saldo.',true);if(!acct)return notify('Selecciona la cuenta donde entró este abono.',true);const next=round(paid(sale)+amount);const payment={id:uid(),date:paymentDate,amount,method:acct.name,accountId:acct.id,accountName:acct.name,note:'Abono'};setBusy(true);try{await setSales(sales.map(s=>s.id===sale.id?{...s,paidAmount:next,status:status(s.amount,next),paymentMethod:s.paymentMethod||acct.name,payments:[...(s.payments||[]),payment]}:s));applyAccountCredit(acct.id,amount,1);setPaymentSale(null);notify(`Abono registrado y sumado a ${acct.name}.`)}catch(err){notify(errMsg(err,'No se pudo guardar el abono.'),true)}finally{setBusy(false)}};
 const remove=async(sale:Sale)=>{if(!confirm('¿Borrar esta venta? El inventario vendido regresará a existencia y los cobros se retirarán de sus cuentas.'))return;setBusy(true);try{await setSales(sales.filter(s=>s.id!==sale.id));if(setAccounts){const byAccount=new Map<string,number>();for(const p of sale.payments||[])if(p.accountId)byAccount.set(p.accountId,(byAccount.get(p.accountId)||0)+p.amount);setAccounts(accountList.map(a=>{const amountC=byAccount.get(a.id)||0;return amountC?{...a,balance:round((Number(a.balance)||0)-accountAmount(amountC,a)),updated:today()}:a}))}await reloadInventory?.();notify('Venta eliminada: inventario restaurado y cobros revertidos de sus cuentas.')}catch(err){notify(errMsg(err,'No se pudo borrar.'),true)}finally{setBusy(false)}};
 const history=sales.find(s=>s.id===historyId);
 return <><div className="totalCircleWrap salesCircleWrap"><div className="totalCircle salesTotalCircle"><div className="circleInner"><span>TOTAL VENTAS DEL MES</span><strong>{money(totalSalesC)}</strong><b>US${(rate>0?totalSalesC/rate:0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}</b><small>{visible.length} {visible.length===1?'venta registrada':'ventas registradas'}</small></div></div><div className="circleBreakdown"><h3>Total actual de ventas</h3><div><span>Ventas del mes</span><b>{dual(totalSalesC,rate)}</b></div><div><span>Cobrado</span><b>{dual(collectedSalesC,rate)}</b></div><div><span>Por cobrar</span><b>{dual(pendingSalesC,rate)}</b></div><div className="circleFormula">Muestra todas las ventas del mes, cuánto dinero ya fue cobrado y cuánto continúa pendiente.</div></div></div><Message text={message} error={error}/>
 <div className="panel editForm" ref={editor}><h2>{editing?'Editar venta completa':'Registro de venta · varios productos'}</h2><p className="editorNotice">Agrega todos los productos y servicios de una misma venta. Los productos elegidos del inventario se descuentan automáticamente; los servicios/manuales no afectan existencias.</p><form onSubmit={save}><fieldset disabled={busy}><div className="form grid"><Field label="Fecha"><input required type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Cliente"><input required value={f.client} onChange={e=>setF({...f,client:e.target.value})}/></Field><CurrencyField value={f.currency} onChange={currency=>setF({...f,currency})}/><Field label="Cuenta donde entra el pago"><select value={f.paymentAccountId} onChange={e=>setF({...f,paymentAccountId:e.target.value})}><option value="">Selecciona una cuenta de Banco y Efectivo</option>{accountList.map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency} · saldo {Number(a.balance).toFixed(2)}</option>)}</select></Field><Field label="Nota / trabajo general"><input value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></Field>{!editing&&<Field label="Pago inicial"><input type="number" min="0" step="0.01" value={f.initialPayment} onChange={e=>setF({...f,initialPayment:e.target.value})}/></Field>}</div>
 <div className="saleLines"><div className="saleLinesHead"><div><h3>Productos y servicios</h3><p>Busca del inventario o escribe manualmente.</p></div><button type="button" className="btn primary" onClick={addLine}>+ Agregar producto / servicio</button></div>{f.lines.map((l,i)=><div className="saleLineCard" key={l.id}><div className="saleLineNumber">#{i+1}</div><div className="lineMode"><button type="button" className={l.mode==='inventory'?'small activeChoice':'small'} onClick={()=>setLine(l.id,{mode:'inventory'})}>Buscar inventario</button><button type="button" className={l.mode==='manual'?'small activeChoice':'small'} onClick={()=>addManual(l.id)}>Escribir manual</button></div>{l.mode==='inventory'?<><Field label="Buscar producto / código"><select value={l.inventoryItemId||''} onChange={e=>pickInventory(l.id,e.target.value)}><option value="">Selecciona del inventario…</option>{inventory.map(p=><option key={p.id} value={p.id}>{p.sku||'SIN-COD'} · {p.name} · Talla {p.talla||'—'} · {p.color||'—'} · Stock {p.qty}</option>)}</select></Field><div className="lineMeta"><span>Código <b>{l.productCode||'—'}</b></span><span>Talla <b>{l.talla||'—'}</b></span><span>Color <b>{l.color||'—'}</b></span></div></>:<div className="form grid"><Field label="Producto / servicio"><input value={l.name} onChange={e=>setLine(l.id,{name:e.target.value})} placeholder="Ej. Impresión DTF, taza, camisa…"/></Field><Field label="Código (opcional)"><input value={l.productCode||''} onChange={e=>setLine(l.id,{productCode:e.target.value})}/></Field><Field label="Talla"><input value={l.talla||''} onChange={e=>setLine(l.id,{talla:e.target.value})} placeholder="Ej. M, L, 18Y"/></Field><Field label="Color"><input value={l.color||''} onChange={e=>setLine(l.id,{color:e.target.value})}/></Field></div>}<div className="form grid lineNumbers"><Field label="Cantidad"><input type="number" min="1" step="1" value={l.quantity} onChange={e=>setLine(l.id,{quantity:Number(e.target.value)})}/></Field><Field label={`Precio unitario ${f.currency}`}><input type="number" min="0" step="0.01" value={l.unitPrice} onChange={e=>setLine(l.id,{unitPrice:Number(e.target.value)})}/></Field><div className="conversion"><span>Subtotal</span><b>{f.currency}{lineTotal(l).toFixed(2)}</b></div><button type="button" className="dangerSmall" onClick={()=>removeLine(l.id)} disabled={f.lines.length===1}>Quitar</button></div></div>)}</div>
 <div className="saleGrandTotal"><span>TOTAL DE LA VENTA</span><strong>{f.currency}{enteredTotal.toFixed(2)}</strong><b>{dual(total,rate)}</b></div><div className="actions"><button className="btn primary" type="submit">{busy?'Guardando…':editing?'Guardar venta completa':'Registrar venta completa'}</button>{editing&&<button type="button" className="btn" onClick={reset}>Cancelar edición</button>}</div></fieldset></form></div>
 <div className="panel" ref={paymentEditor}>{paymentSale&&<><h2>Registrar abono · {sales.find(s=>s.id===paymentSale)?.client}</h2><form onSubmit={addPayment}><fieldset className="form grid" disabled={busy}><Field label="Fecha"><input type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></Field><Field label="Abono en C$"><input type="number" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)}/></Field><Field label="Cuenta donde entró"><select value={paymentAccountId} onChange={e=>setPaymentAccountId(e.target.value)}><option value="">Selecciona cuenta</option>{accountList.map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></Field><button className="btn primary">Guardar abono</button></fieldset></form></>}<h2>Ventas · {month}</h2><GridTable heads={['Fecha','Cliente','Detalle de venta','Método','Total','Pagado','Saldo','Estado','Acciones']}>{visible.map(s=><tr key={s.id}><td>{s.date}</td><td>{s.client}</td><td><b>{s.lineItems?.length||1} línea(s)</b><br/><small>{(s.lineItems?.length?s.lineItems.map(l=>`${l.quantity}× ${l.name}${l.talla?' '+l.talla:''}`).join(' · '):s.productName||s.description)}</small></td><td><span className="methodBadge other">{(s.payments||[]).slice(-1)[0]?.accountName||s.paymentMethod||'Por cobrar'}</span></td><td>{money(s.amount)}</td><td>{money(paid(s))}</td><td>{money(Math.max(0,s.amount-paid(s)))}</td><td>{s.status}</td><td><div className="actions"><button className="small" onClick={()=>edit(s)}>Editar</button><button className="small" disabled={paid(s)>=s.amount} onClick={()=>{setPaymentSale(s.id);setPaymentAmount(String(round(s.amount-paid(s))));setPaymentAccountId((s.payments||[]).slice(-1)[0]?.accountId||accountList[0]?.id||'')}}>+ Abono</button><button className="small" onClick={()=>setHistoryId(historyId===s.id?null:s.id)}>Historial</button><button className="dangerSmall" onClick={()=>remove(s)}>Borrar</button></div></td></tr>)}</GridTable></div>{history&&<div className="panel"><h2>Detalle · {history.client}</h2><GridTable heads={['Código','Producto/servicio','Talla','Color','Cantidad','P. unitario']}>{(history.lineItems||[]).map(l=><tr key={l.id}><td>{l.productCode||'—'}</td><td>{l.name}</td><td>{l.talla||'—'}</td><td>{l.color||'—'}</td><td>{l.quantity}</td><td>{history.currency}{l.unitPrice.toFixed(2)}</td></tr>)}</GridTable><h3>Pagos</h3><GridTable heads={['Fecha','Cuenta destino','Importe']}>{history.payments?.map(p=><tr key={p.id}><td>{p.date}</td><td>{p.accountName||p.method||'Sin cuenta (registro antiguo)'}</td><td>{money(p.amount)}</td></tr>)}</GridTable></div>}</>;
}
const DEFAULT_EXPENSE_CATEGORIES=['Materiales','Operativo','Servicios','Transporte','Nómina','Publicidad','Equipos','Otro'];
export function Expenses({expenses,setExpenses,accounts,setAccounts,month,rate,expenseCategories,addExpenseCategory,removeExpenseCategory,expensePaymentMethods,addExpensePaymentMethod,removeExpensePaymentMethod}:{expenses:Expense[];setExpenses:Setter<Expense>;accounts?:any[];setAccounts?:Setter<any>;month:string;rate:number;expenseCategories?:string[];addExpenseCategory?:(name:string)=>Promise<void>;removeExpenseCategory?:(name:string)=>Promise<void>;expensePaymentMethods?:string[];addExpensePaymentMethod?:(name:string)=>Promise<void>;removeExpensePaymentMethod?:(name:string)=>Promise<void>}){
 const categories=(expenseCategories&&expenseCategories.length)?expenseCategories:DEFAULT_EXPENSE_CATEGORIES;
 const expenseMethods=(expensePaymentMethods&&expensePaymentMethods.length)?expensePaymentMethods:['Efectivo','Transferencia / BAC'];
 const empty=()=>({date:today(),category:categories[0]||'Operativo',description:'',amount:'',currency:'C$' as Currency,paymentChannel:'Efectivo',sourceAccountId:''});
 const [f,setF]=useState(empty),[editing,setEditing]=useState<Expense|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);const editor=useRef<HTMLDivElement>(null);
 const accountList=(accounts||[]) as any[];
 const matchingAccounts=accountList;
 const selectedAccount=matchingAccounts.find(a=>a.id===f.sourceAccountId)||matchingAccounts.find(a=>a.currency===f.currency)||matchingAccounts[0];
 const reset=()=>{setEditing(null);setF(empty())};
 const edit=(x:Expense)=>{setEditing(x);setF({date:x.date,category:x.category,description:x.description,amount:String(x.enteredAmount??x.amount/(x.currency==='US$'?rate:1)),currency:x.currency||'C$',paymentChannel:x.paymentChannel||(/efectivo|caja/i.test(x.sourceAccountName||'')?'Efectivo':'Transferencia / BAC'),sourceAccountId:x.sourceAccountId||''});setMessage('');editor.current?.scrollIntoView({behavior:'smooth'})};
 const handleAddCategory=async()=>{const name=prompt('Nombre de la nueva categoría de gasto:');if(!name||!name.trim())return;if(!addExpenseCategory){alert('No se pudo guardar la nueva categoría.');return}try{await addExpenseCategory(name.trim());setF(prev=>({...prev,category:name.trim()}))}catch(err){console.error(err);alert(errMsg(err,'No se pudo guardar la nueva categoría en la nube. Inténtalo de nuevo.'))}};
 const handleRemoveCategoryItem=async(name:string)=>{if(!removeExpenseCategory){alert('No se pudo borrar la categoría.');return}try{await removeExpenseCategory(name);setF(prev=>prev.category===name?{...prev,category:categories.filter(c=>c!==name)[0]||''}:prev)}catch(err){console.error(err);alert(errMsg(err,'No se pudo borrar la categoría en la nube. Inténtalo de nuevo.'))}};
 const handleAddExpenseMethod=async()=>{const name=prompt('Nueva forma de pago:');if(!name||!name.trim()||!addExpensePaymentMethod)return;try{await addExpensePaymentMethod(name.trim());setF(prev=>({...prev,paymentChannel:name.trim(),sourceAccountId:''}))}catch(err){alert(errMsg(err,'No se pudo guardar la forma de pago.'))}};
 const handleRemoveExpenseMethod=async(name:string)=>{if(!removeExpensePaymentMethod)return;try{await removeExpensePaymentMethod(name);setF(prev=>prev.paymentChannel===name?{...prev,paymentChannel:expenseMethods.find(x=>x!==name)||'Efectivo',sourceAccountId:''}:prev)}catch(err){alert(errMsg(err,'No se pudo borrar la forma de pago.'))}};
 const applyLocalAccountChange=(oldExpense:Expense|null,newExpense:Expense|null)=>{
  if(!setAccounts||!accounts)return;
  const next=accountList.map(a=>{
   let balance=Number(a.balance)||0;
   if(oldExpense && oldExpense.sourceAccountId===a.id) balance+=Number(oldExpense.enteredAmount??(oldExpense.currency==='US$'?oldExpense.amount/rate:oldExpense.amount));
   if(newExpense && newExpense.sourceAccountId===a.id) balance-=Number(newExpense.enteredAmount??(newExpense.currency==='US$'?newExpense.amount/rate:newExpense.amount));
   return balance===a.balance?a:{...a,balance,updated:today()};
  });
  setAccounts(next);
 };
 const save=async(e:FormEvent)=>{e.preventDefault();if(busy)return;const original=editing?.enteredAmount??(editing?editing.amount/(editing.currency==='US$'?rate:1):0);const amount=editing&&Number(f.amount)===original&&f.currency===(editing.currency||'C$')?editing.amount:convert(f.amount,f.currency,rate);
  const acct=matchingAccounts.find(a=>a.id===(f.sourceAccountId||selectedAccount?.id));
  if(!f.description.trim()||!f.date||!Number.isFinite(amount)||amount<=0||rate<=0){setError(true);setMessage('Completa fecha, descripción y un importe válido mayor que cero.');return}
  if(!acct){setError(true);setMessage('No hay una cuenta seleccionada. Créala primero en Banco y Efectivo.');return}
  const entered=Number(f.amount);const available=Number(acct.balance)||0;const restored=editing && editing.sourceAccountId===acct.id ? Number(editing.enteredAmount ?? (editing.currency==='US$' ? editing.amount/rate : editing.amount)) : 0;
  if(entered>available+restored){setError(true);setMessage(`Saldo insuficiente en ${acct.name}. Disponible: ${acct.currency}${(available+restored).toFixed(2)}.`);return}
  const row:Expense={id:editing?.id||uid(),date:f.date,category:f.category,description:f.description.trim(),amount,currency:f.currency,enteredAmount:entered,paymentChannel:f.paymentChannel,sourceAccountId:acct.id,sourceAccountName:acct.name};
  setBusy(true);try{await setExpenses(editing?expenses.map(x=>x.id===editing.id?row:x):[...expenses,row]);applyLocalAccountChange(editing,row);setError(false);setMessage(editing?'Gasto actualizado y saldo ajustado.':'Gasto registrado y descontado de '+acct.name+'.');reset()}catch(err){setError(true);setMessage(errMsg(err,'No se pudo guardar el gasto.'))}finally{setBusy(false)}
 };
 const remove=async(x:Expense)=>{if(!confirm('¿Borrar este gasto? El importe regresará a la cuenta de origen.'))return;setBusy(true);try{await setExpenses(expenses.filter(z=>z.id!==x.id));applyLocalAccountChange(x,null);if(editing?.id===x.id)reset();setError(false);setMessage('Gasto eliminado y saldo restaurado.')}catch(err){setError(true);setMessage(errMsg(err,'No se pudo borrar el gasto.'))}finally{setBusy(false)}};
 const visible=expenses.filter(x=>x.date.startsWith(month)).slice().reverse();
 const sum=(currency:Currency,channel?:string)=>visible.filter(x=>x.currency===currency&&(!channel||x.paymentChannel===channel)).reduce((n,x)=>n+Number(x.enteredAmount??(currency==='US$'?x.amount/rate:x.amount)),0);
 const totalExpensesC=visible.reduce((n,x)=>n+Number(x.amount||0),0);
 return <><Message text={message} error={error}/>
 <div className="totalCircleWrap expenseCircleWrap"><div className="totalCircle expenseTotalCircle"><div className="circleInner"><span>TOTAL GASTOS DEL MES</span><strong>C${totalExpensesC.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}</strong><b>US${(rate>0?totalExpensesC/rate:0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}</b><small>{visible.length} {visible.length===1?'gasto registrado':'gastos registrados'}</small></div></div><div className="circleBreakdown"><h3>Total actual de gastos</h3><div><span>Valor en córdobas</span><b>C${totalExpensesC.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}</b></div><div><span>Equivalente en dólares</span><b>US${(rate>0?totalExpensesC/rate:0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}</b></div><div className="circleFormula">Suma todos los gastos registrados en el mes seleccionado, sin importar de cuál cuenta salieron. La conversión usa el tipo de cambio actual.</div></div></div>
 <div className="paymentSummary expenseSummary"><div className="card"><span>EFECTIVO C$</span><strong>C${sum('C$','Efectivo').toFixed(2)}</strong><small>Gastos pagados desde efectivo</small></div><div className="card"><span>EFECTIVO US$</span><strong>US${sum('US$','Efectivo').toFixed(2)}</strong><small>Gastos pagados desde efectivo dólar</small></div><div className="card"><span>BAC C$</span><strong>C${sum('C$','Transferencia / BAC').toFixed(2)}</strong><small>Gastos pagados desde banco</small></div><div className="card"><span>BAC US$</span><strong>US${sum('US$','Transferencia / BAC').toFixed(2)}</strong><small>Gastos pagados desde banco dólar</small></div></div>
 <div className="panel editForm" ref={editor}><h2>{editing?'Editar gasto':'Registro de gastos'}</h2><p className="editorNotice">El gasto se descuenta automáticamente de la cuenta elegida según moneda y forma de pago.</p><form onSubmit={save}><fieldset disabled={busy} className="form grid"><Field label="Fecha"><input required type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><label><span>Categoría <button type="button" className="addChip" onClick={handleAddCategory} title="Agregar categoría">+</button></span><ManagedSelect value={f.category} onChange={v=>setF({...f,category:v})} options={categories} onRemove={handleRemoveCategoryItem} confirmMessage={(c:string)=>`¿Borrar la categoría "${c}" de tu lista? Los gastos que ya la tienen la conservan igual.`}/></label><Field label="Descripción"><input required value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></Field><Field label="Monto"><input required type="number" min="0.01" step="0.01" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></Field><CurrencyField value={f.currency} onChange={currency=>setF({...f,currency})}/><label><span>Forma de pago <button type="button" className="addChip" onClick={handleAddExpenseMethod} title="Agregar forma de pago">+</button></span><ManagedSelect value={f.paymentChannel} onChange={v=>setF({...f,paymentChannel:v})} options={expenseMethods} onRemove={handleRemoveExpenseMethod}/></label><Field label="Sale de la cuenta"><select value={f.sourceAccountId||selectedAccount?.id||''} onChange={e=>{const a=accountList.find(x=>x.id===e.target.value);setF({...f,sourceAccountId:e.target.value,currency:(a?.currency||f.currency) as Currency})}}><option value="">Selecciona cuenta</option>{accountList.map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency} · saldo {Number(a.balance).toFixed(2)}</option>)}</select></Field><div className="actions"><button type="submit" className="btn primary">{busy?'Guardando…':editing?'Guardar cambios':'Guardar gasto'}</button>{editing&&<button type="button" className="btn" onClick={reset}>Cancelar edición</button>}</div></fieldset></form></div>
 <div className="panel"><h2>Historial de gastos · {month}</h2><GridTable heads={['Fecha','Categoría','Descripción','Forma','Cuenta','Importe','Acciones']}>{visible.map(x=><tr key={x.id}><td>{x.date}</td><td>{x.category}</td><td>{x.description}</td><td>{x.paymentChannel||'Sin clasificar'}</td><td>{x.sourceAccountName||'—'}</td><td>{x.currency==='US$'?'US$':'C$'}{Number(x.enteredAmount??(x.currency==='US$'?x.amount/rate:x.amount)).toFixed(2)}</td><td><div className="actions"><button className="small" disabled={busy} onClick={()=>edit(x)}>Editar</button><button className="dangerSmall" disabled={busy} onClick={()=>remove(x)}>Borrar</button></div></td></tr>)}</GridTable>{!visible.length&&<p className="empty">No hay gastos en este mes.</p>}</div></>;
}
export function SalesMethods({sales,month,rate,accounts=[]}:SalesProps){
 const [all,setAll]=useState(false);const payments=sales.flatMap(s=>(s.payments||[]).map(p=>({...p,client:s.client,saleId:s.id}))).filter(p=>all||p.date.startsWith(month)).sort((a,b)=>b.date.localeCompare(a.date));
 const accountList=accounts as any[];const groups=[...accountList.map(a=>a.name),'Sin cuenta (antiguos)'];
 return <><div className="panel"><h2>Cobros por cuenta</h2><p className="muted">Cada cobro se registra en la cuenta exacta elegida en Banco y Efectivo. Las cuentas nuevas aparecen aquí automáticamente.</p><Field label="Período del historial"><select value={all?'all':'month'} onChange={e=>setAll(e.target.value==='all')}><option value="month">Mes seleccionado: {month}</option><option value="all">Todo el historial</option></select></Field></div>
 <div className="paymentSummary">{groups.map(name=>{const rows=payments.filter(p=>(p.accountName||'Sin cuenta (antiguos)')===name);return <div className="card" key={name}><span>{name}</span><strong>{dual(rows.reduce((n,p)=>n+p.amount,0),rate)}</strong><small>{rows.length} cobro(s) registrado(s)</small></div>})}</div>
 <div className="panel"><h2>Historial de cobros</h2><GridTable heads={['Fecha','Cliente','Cuenta destino','Importe']}>{payments.map(p=><tr key={p.id}><td>{p.date}</td><td>{p.client}</td><td>{p.accountName||p.method||'Sin cuenta (registro antiguo)'}</td><td>{dual(p.amount,rate)}</td></tr>)}</GridTable>{!payments.length&&<p className="empty">No hay cobros en este período.</p>}</div></>;
}
